### ISSUE TITLE
Usage of discord wrappers for commands.

### ISSUE THREAD

**Issue by LeoJit** [AndyReifman/ArseneWenger#21]
Currently you seem to be using a listener for commands, and hence everything is stacked in one file. I'd suggest you use:
- Cogs (Basically multiple files with commands of similar type)
- Discord.py wrapper for commands and other parts

Which would help anyone understand the code at first glance, and also make updating the code easier for the devs.

**Comment by ash663** [comment]
@LeoJit Do cogs make better use of resources? Asking to gauge the priority of this task
