### ISSUE TITLE
Holding - Create CI/CD pipeline

### ISSUE THREAD

**Issue by ingenium21** [AndyReifman/ArseneWenger#32]
This is an issue to hold and track any progress we've made in the CI/CD pipeline.

**Comment by AndyReifman** [comment]
Before we get to the pipeline I think we need to come up with some base tests that we expect to pass any time a change is committed. Even if I'm executing those by hand for the time being, I think that's a better place to start. Choose a tool based on what we are doing, don't do stuff based on the tool we choose.

**Comment by ash663** [comment]
To start with, our tests can simply check for expected <object>
Example:
`!next` outputs ```Next match is Burnley (H) in 15 hours, 6 minutes```
Strip out ``Next match is` and check `Burnley (H) in 15 hours, 6 minutes` is a non-empty string.
