### ISSUE TITLE
!next command does not display correct information when a match is being played

### ISSUE THREAD

**Issue by AndyReifman** [AndyReifman/ArseneWenger#45]
```
[10:28] Eabryt: !next
[10:28] BOT
 Arsene Wenger:
Next match is Burnley (H) in 22 hours, 31 minutes
```

I propose we change this to say "Arsenal are playing X right now." or something of that style.

**Comment by ingenium21** [comment]
it's not a bug it's a feature 😏

**Comment by ingenium21** [comment]
i'll probably add some code where it says "if next match - utc.now() is negative, display "match is already underway"

**Comment by ingenium21** [comment]
marking this as closed as we have resolved the issue.
