### ISSUE TITLE
Switch from requests to aiohttp

### ISSUE THREAD

**Issue by FelixRandle** [AndyReifman/ArseneWenger#63]
The requests library isn't asynchronous so on longer requests it blocks operation of the bot whilst the request is being handled

Should switch over to [aiohttp](https://docs.aiohttp.org/en/stable/) which fully supports async/await

**Comment by ash663** [comment]
If we do switch over to aiohttp, we should do it safely. There's a decent chance people will abuse the bot by spamming commands and opening up multiple threads can bring down the server. We need some sort of loadshedding in the bot and decide on the maximum number of threads we want open at any point of time
